language: python
python:
  - "2.7"

env:
  - TOX_ENV=docs
  - TOX_ENV=lint
  - TOX_ENV=py26
  - TOX_ENV=py27

install:
  - git submodule update --init --recursive
  - pip install -U pip setuptools tox
  - sudo apt-get install -qq lib32z1 lib32ncurses5 lib32bz2-1.0 # temporarily

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e coverage

notifications:
  slack:
    secure: ksQmXOP5NVsf8IgoDuxD68Q/YNwDpZuwq0V29h2dxYCr38oYdAkq/Os4LSCs0X6P0cQFf6nC1hM/d+cAvU+SmzcHGxEceHNEGCg3/TAj+68KIwooPU93Lfq1zwdfteZWxANjKlCQy4+wZliHLhL8fvCYgfJww/6qKmqSYleBNM=
    on_failure: always
    on_success: change
