cache:
    directories:
        - $HOME/.platformio 

language: python
python:
    - "2.6"
    - "2.7"

env:
    - TOX_ENV=docs
    - TOX_ENV=lint
    - TOX_ENV=py27       

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
