build: off
environment:

  matrix:
    - TOXENV: "py27"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=%PATH%;C:\Python27\Scripts;C:\MinGW\bin
  - cmd: pip install tox

test_script:
  - cmd: tox

notifications:
  - provider: Email
    to:
      - me@ikravets.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

  - provider: Slack
    incoming_webhook:
      secure: E9H0SU0Ju7WLDvgxsV8cs3J62T3nTTX7QkEjsczN0Sto/c9hWkVfhc5gGWUkxhlD975cokHByKGJIdwYwCewqOI+7BrcT8U+nlga4Uau7J8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
